// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: web/v1/article_class.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文章分类列表接口请求参数
type ArticleClassListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassListRequest) Reset() {
	*x = ArticleClassListRequest{}
	mi := &file_web_v1_article_class_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassListRequest) ProtoMessage() {}

func (x *ArticleClassListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassListRequest.ProtoReflect.Descriptor instead.
func (*ArticleClassListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{0}
}

// 文章分类列表接口响应参数
type ArticleClassListResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*ArticleClassListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassListResponse) Reset() {
	*x = ArticleClassListResponse{}
	mi := &file_web_v1_article_class_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassListResponse) ProtoMessage() {}

func (x *ArticleClassListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassListResponse.ProtoReflect.Descriptor instead.
func (*ArticleClassListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleClassListResponse) GetItems() []*ArticleClassListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 文章分类编辑接口请求参数
type ArticleClassEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassifyId    int32                  `protobuf:"varint,1,opt,name=classify_id,json=classifyId,proto3" json:"classify_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassEditRequest) Reset() {
	*x = ArticleClassEditRequest{}
	mi := &file_web_v1_article_class_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassEditRequest) ProtoMessage() {}

func (x *ArticleClassEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassEditRequest.ProtoReflect.Descriptor instead.
func (*ArticleClassEditRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{2}
}

func (x *ArticleClassEditRequest) GetClassifyId() int32 {
	if x != nil {
		return x.ClassifyId
	}
	return 0
}

func (x *ArticleClassEditRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 文章分类编辑接口响应参数
type ArticleClassEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassifyId    int32                  `protobuf:"varint,1,opt,name=classify_id,json=classifyId,proto3" json:"classify_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassEditResponse) Reset() {
	*x = ArticleClassEditResponse{}
	mi := &file_web_v1_article_class_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassEditResponse) ProtoMessage() {}

func (x *ArticleClassEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassEditResponse.ProtoReflect.Descriptor instead.
func (*ArticleClassEditResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleClassEditResponse) GetClassifyId() int32 {
	if x != nil {
		return x.ClassifyId
	}
	return 0
}

// 文章分类删除接口请求参数
type ArticleClassDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassifyId    int32                  `protobuf:"varint,1,opt,name=classify_id,json=classifyId,proto3" json:"classify_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassDeleteRequest) Reset() {
	*x = ArticleClassDeleteRequest{}
	mi := &file_web_v1_article_class_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassDeleteRequest) ProtoMessage() {}

func (x *ArticleClassDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassDeleteRequest.ProtoReflect.Descriptor instead.
func (*ArticleClassDeleteRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleClassDeleteRequest) GetClassifyId() int32 {
	if x != nil {
		return x.ClassifyId
	}
	return 0
}

// 文章分类删除接口响应参数
type ArticleClassDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassDeleteResponse) Reset() {
	*x = ArticleClassDeleteResponse{}
	mi := &file_web_v1_article_class_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassDeleteResponse) ProtoMessage() {}

func (x *ArticleClassDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassDeleteResponse.ProtoReflect.Descriptor instead.
func (*ArticleClassDeleteResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{5}
}

// 文章分类排序接口请求参数
type ArticleClassSortRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 排序后的分类ID列表
	ClassifyIds   []int32 `protobuf:"varint,1,rep,packed,name=classify_ids,json=classifyIds,proto3" json:"classify_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassSortRequest) Reset() {
	*x = ArticleClassSortRequest{}
	mi := &file_web_v1_article_class_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassSortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassSortRequest) ProtoMessage() {}

func (x *ArticleClassSortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassSortRequest.ProtoReflect.Descriptor instead.
func (*ArticleClassSortRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{6}
}

func (x *ArticleClassSortRequest) GetClassifyIds() []int32 {
	if x != nil {
		return x.ClassifyIds
	}
	return nil
}

// 文章分类排序接口响应参数
type ArticleClassSortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassSortResponse) Reset() {
	*x = ArticleClassSortResponse{}
	mi := &file_web_v1_article_class_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassSortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassSortResponse) ProtoMessage() {}

func (x *ArticleClassSortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassSortResponse.ProtoReflect.Descriptor instead.
func (*ArticleClassSortResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{7}
}

type ArticleClassListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	IsDefault     int32                  `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleClassListResponse_Item) Reset() {
	*x = ArticleClassListResponse_Item{}
	mi := &file_web_v1_article_class_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleClassListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleClassListResponse_Item) ProtoMessage() {}

func (x *ArticleClassListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_article_class_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleClassListResponse_Item.ProtoReflect.Descriptor instead.
func (*ArticleClassListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_article_class_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ArticleClassListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleClassListResponse_Item) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ArticleClassListResponse_Item) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ArticleClassListResponse_Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_web_v1_article_class_proto protoreflect.FileDescriptor

const file_web_v1_article_class_proto_rawDesc = "" +
	"\n" +
	"\x1aweb/v1/article_class.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x19\n" +
	"\x17ArticleClassListRequest\"\xdf\x01\n" +
	"\x18ArticleClassListResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2\".web.ArticleClassListResponse.ItemB\x04\xe2A\x01\x02R\x05items\x1a\x82\x01\n" +
	"\x04Item\x12\x14\n" +
	"\x02id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x02id\x12#\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\tclassName\x12#\n" +
	"\n" +
	"is_default\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\tisDefault\x12\x1a\n" +
	"\x05count\x18\x04 \x01(\x05B\x04\xe2A\x01\x02R\x05count\"[\n" +
	"\x17ArticleClassEditRequest\x12\x1f\n" +
	"\vclassify_id\x18\x01 \x01(\x05R\n" +
	"classifyId\x12\x1f\n" +
	"\x04name\x18\x02 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\x04name\"A\n" +
	"\x18ArticleClassEditResponse\x12%\n" +
	"\vclassify_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\n" +
	"classifyId\"I\n" +
	"\x19ArticleClassDeleteRequest\x12,\n" +
	"\vclassify_id\x18\x01 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\n" +
	"classifyId\"\x1c\n" +
	"\x1aArticleClassDeleteResponse\"J\n" +
	"\x17ArticleClassSortRequest\x12/\n" +
	"\fclassify_ids\x18\x01 \x03(\x05B\f\xe2A\x01\x02\xbaH\x05\x92\x01\x02\b\x01R\vclassifyIds\"\x1a\n" +
	"\x18ArticleClassSortResponse2\xd2\x03\n" +
	"\fArticleClass\x12m\n" +
	"\x04List\x12\x1c.web.ArticleClassListRequest\x1a\x1d.web.ArticleClassListResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/article/classify/list\x12m\n" +
	"\x04Edit\x12\x1c.web.ArticleClassEditRequest\x1a\x1d.web.ArticleClassEditResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/article/classify/edit\x12u\n" +
	"\x06Delete\x12\x1e.web.ArticleClassDeleteRequest\x1a\x1f.web.ArticleClassDeleteResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/article/classify/delete\x12m\n" +
	"\x04Sort\x12\x1c.web.ArticleClassSortRequest\x1a\x1d.web.ArticleClassSortResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/article/classify/sortB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_article_class_proto_rawDescOnce sync.Once
	file_web_v1_article_class_proto_rawDescData []byte
)

func file_web_v1_article_class_proto_rawDescGZIP() []byte {
	file_web_v1_article_class_proto_rawDescOnce.Do(func() {
		file_web_v1_article_class_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_article_class_proto_rawDesc), len(file_web_v1_article_class_proto_rawDesc)))
	})
	return file_web_v1_article_class_proto_rawDescData
}

var file_web_v1_article_class_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_web_v1_article_class_proto_goTypes = []any{
	(*ArticleClassListRequest)(nil),       // 0: web.ArticleClassListRequest
	(*ArticleClassListResponse)(nil),      // 1: web.ArticleClassListResponse
	(*ArticleClassEditRequest)(nil),       // 2: web.ArticleClassEditRequest
	(*ArticleClassEditResponse)(nil),      // 3: web.ArticleClassEditResponse
	(*ArticleClassDeleteRequest)(nil),     // 4: web.ArticleClassDeleteRequest
	(*ArticleClassDeleteResponse)(nil),    // 5: web.ArticleClassDeleteResponse
	(*ArticleClassSortRequest)(nil),       // 6: web.ArticleClassSortRequest
	(*ArticleClassSortResponse)(nil),      // 7: web.ArticleClassSortResponse
	(*ArticleClassListResponse_Item)(nil), // 8: web.ArticleClassListResponse.Item
}
var file_web_v1_article_class_proto_depIdxs = []int32{
	8, // 0: web.ArticleClassListResponse.items:type_name -> web.ArticleClassListResponse.Item
	0, // 1: web.ArticleClass.List:input_type -> web.ArticleClassListRequest
	2, // 2: web.ArticleClass.Edit:input_type -> web.ArticleClassEditRequest
	4, // 3: web.ArticleClass.Delete:input_type -> web.ArticleClassDeleteRequest
	6, // 4: web.ArticleClass.Sort:input_type -> web.ArticleClassSortRequest
	1, // 5: web.ArticleClass.List:output_type -> web.ArticleClassListResponse
	3, // 6: web.ArticleClass.Edit:output_type -> web.ArticleClassEditResponse
	5, // 7: web.ArticleClass.Delete:output_type -> web.ArticleClassDeleteResponse
	7, // 8: web.ArticleClass.Sort:output_type -> web.ArticleClassSortResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_web_v1_article_class_proto_init() }
func file_web_v1_article_class_proto_init() {
	if File_web_v1_article_class_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_article_class_proto_rawDesc), len(file_web_v1_article_class_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_article_class_proto_goTypes,
		DependencyIndexes: file_web_v1_article_class_proto_depIdxs,
		MessageInfos:      file_web_v1_article_class_proto_msgTypes,
	}.Build()
	File_web_v1_article_class_proto = out.File
	file_web_v1_article_class_proto_goTypes = nil
	file_web_v1_article_class_proto_depIdxs = nil
}
