// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IArticleHandler BFF 接口
type IArticleHandler interface {

	// 文章编辑接口
	Edit(ctx context.Context, in *ArticleEditRequest) (*ArticleEditResponse, error)
	// 获取文章详情接口
	Detail(ctx context.Context, in *ArticleDetailRequest) (*ArticleDetailResponse, error)
	// 获取文章列表接口
	List(ctx context.Context, in *ArticleListRequest) (*ArticleListResponse, error)
	// 删除文章接口
	Delete(ctx context.Context, in *ArticleDeleteRequest) (*ArticleDeleteResponse, error)
	// 恢复文章接口
	Recover(ctx context.Context, in *ArticleRecoverRequest) (*ArticleRecoverResponse, error)
	// 永久删除文章接口
	ForeverDelete(ctx context.Context, in *ArticleForeverDeleteRequest) (*ArticleForeverDeleteResponse, error)
	// 移动文章分类接口
	Move(ctx context.Context, in *ArticleMoveRequest) (*ArticleMoveResponse, error)
	// 收藏/取消收藏文章接口
	Asterisk(ctx context.Context, in *ArticleAsteriskRequest) (*ArticleAsteriskResponse, error)
	// 设置文章标签接口
	SetTags(ctx context.Context, in *ArticleTagsRequest) (*ArticleTagsResponse, error)
	// 获取回收站文章列表接口
	RecoverList(ctx context.Context, in *ArticleRecoverListRequest) (*ArticleRecoverListResponse, error)
}

// RegisterArticleHandler 注册服务路由处理器
func RegisterArticleHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler IArticleHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/article/editor", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleEditRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Edit(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/detail", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleDetailRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Detail(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.List(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/delete", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleDeleteRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Delete(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/recover", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleRecoverRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Recover(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/forever-delete", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleForeverDeleteRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.ForeverDelete(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/move", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleMoveRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Move(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/asterisk", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleAsteriskRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Asterisk(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/tags", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleTagsRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SetTags(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/article/recover-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ArticleRecoverListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.RecoverList(ctx.Request.Context(), &in)
	}))

}
