// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: web/v1/common.proto

package web

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送短信验证码接口请求参数
type CommonSendSmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile  string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *CommonSendSmsRequest) Reset() {
	*x = CommonSendSmsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonSendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendSmsRequest) ProtoMessage() {}

func (x *CommonSendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendSmsRequest.ProtoReflect.Descriptor instead.
func (*CommonSendSmsRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonSendSmsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CommonSendSmsRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

// 发送短信验证码接口响应参数
type CommonSendSmsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmsCode string `protobuf:"bytes,1,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
}

func (x *CommonSendSmsResponse) Reset() {
	*x = CommonSendSmsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonSendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendSmsResponse) ProtoMessage() {}

func (x *CommonSendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendSmsResponse.ProtoReflect.Descriptor instead.
func (*CommonSendSmsResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *CommonSendSmsResponse) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

// 发送邮件验证码接口请求参数
type CommonSendEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CommonSendEmailRequest) Reset() {
	*x = CommonSendEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonSendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendEmailRequest) ProtoMessage() {}

func (x *CommonSendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendEmailRequest.ProtoReflect.Descriptor instead.
func (*CommonSendEmailRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *CommonSendEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 发送邮件验证码接口响应参数
type CommonSendEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommonSendEmailResponse) Reset() {
	*x = CommonSendEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonSendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendEmailResponse) ProtoMessage() {}

func (x *CommonSendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendEmailResponse.ProtoReflect.Descriptor instead.
func (*CommonSendEmailResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{3}
}

// 发送邮件验证码接口请求参数
type CommonSendTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CommonSendTestRequest) Reset() {
	*x = CommonSendTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonSendTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendTestRequest) ProtoMessage() {}

func (x *CommonSendTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendTestRequest.ProtoReflect.Descriptor instead.
func (*CommonSendTestRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *CommonSendTestRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 发送邮件验证码接口响应参数
type CommonSendTestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommonSendTestResponse) Reset() {
	*x = CommonSendTestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonSendTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendTestResponse) ProtoMessage() {}

func (x *CommonSendTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendTestResponse.ProtoReflect.Descriptor instead.
func (*CommonSendTestResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{5}
}

var File_web_v1_common_proto protoreflect.FileDescriptor

var file_web_v1_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x77, 0x65, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x77, 0x65, 0x62, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x96, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x06, 0x6d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72,
	0x03, 0x98, 0x01, 0x0b, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x5c, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x42, 0xfa,
	0x42, 0x3f, 0x72, 0x3d, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x0e, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0a, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x62, 0x69, 0x6e,
	0x64, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x32, 0x0a, 0x15, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6d, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x37,
	0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x06,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x36, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72,
	0x02, 0x10, 0x06, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc2, 0x02, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12,
	0x64, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x12, 0x19, 0x2e, 0x77, 0x65, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x3a, 0x01, 0x2a, 0x22, 0x17, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x6e,
	0x64, 0x2d, 0x73, 0x6d, 0x73, 0x12, 0x6c, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1b, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53,
	0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x2d, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x64, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x77, 0x65,
	0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x3a, 0x01, 0x2a, 0x22,
	0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x73, 0x65, 0x6e, 0x64, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x77, 0x65, 0x62,
	0x2f, 0x76, 0x31, 0x3b, 0x77, 0x65, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web_v1_common_proto_rawDescOnce sync.Once
	file_web_v1_common_proto_rawDescData = file_web_v1_common_proto_rawDesc
)

func file_web_v1_common_proto_rawDescGZIP() []byte {
	file_web_v1_common_proto_rawDescOnce.Do(func() {
		file_web_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_v1_common_proto_rawDescData)
	})
	return file_web_v1_common_proto_rawDescData
}

var file_web_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_web_v1_common_proto_goTypes = []any{
	(*CommonSendSmsRequest)(nil),    // 0: web.CommonSendSmsRequest
	(*CommonSendSmsResponse)(nil),   // 1: web.CommonSendSmsResponse
	(*CommonSendEmailRequest)(nil),  // 2: web.CommonSendEmailRequest
	(*CommonSendEmailResponse)(nil), // 3: web.CommonSendEmailResponse
	(*CommonSendTestRequest)(nil),   // 4: web.CommonSendTestRequest
	(*CommonSendTestResponse)(nil),  // 5: web.CommonSendTestResponse
}
var file_web_v1_common_proto_depIdxs = []int32{
	0, // 0: web.Common.SendSms:input_type -> web.CommonSendSmsRequest
	2, // 1: web.Common.SendEmail:input_type -> web.CommonSendEmailRequest
	4, // 2: web.Common.Test:input_type -> web.CommonSendTestRequest
	1, // 3: web.Common.SendSms:output_type -> web.CommonSendSmsResponse
	3, // 4: web.Common.SendEmail:output_type -> web.CommonSendEmailResponse
	5, // 5: web.Common.Test:output_type -> web.CommonSendTestResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_web_v1_common_proto_init() }
func file_web_v1_common_proto_init() {
	if File_web_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web_v1_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommonSendSmsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CommonSendSmsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_common_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CommonSendEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_common_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CommonSendEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_common_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CommonSendTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_common_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CommonSendTestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_v1_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_common_proto_goTypes,
		DependencyIndexes: file_web_v1_common_proto_depIdxs,
		MessageInfos:      file_web_v1_common_proto_msgTypes,
	}.Build()
	File_web_v1_common_proto = out.File
	file_web_v1_common_proto_rawDesc = nil
	file_web_v1_common_proto_goTypes = nil
	file_web_v1_common_proto_depIdxs = nil
}
