// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: web/v1/contact.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 联系人列表接口请求参数
type ContactListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactListRequest) Reset() {
	*x = ContactListRequest{}
	mi := &file_web_v1_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListRequest) ProtoMessage() {}

func (x *ContactListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListRequest.ProtoReflect.Descriptor instead.
func (*ContactListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{0}
}

// 联系人列表接口响应参数
type ContactListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*ContactListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactListResponse) Reset() {
	*x = ContactListResponse{}
	mi := &file_web_v1_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListResponse) ProtoMessage() {}

func (x *ContactListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListResponse.ProtoReflect.Descriptor instead.
func (*ContactListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{1}
}

func (x *ContactListResponse) GetItems() []*ContactListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 联系人删除接口请求参数
type ContactDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactDeleteRequest) Reset() {
	*x = ContactDeleteRequest{}
	mi := &file_web_v1_contact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDeleteRequest) ProtoMessage() {}

func (x *ContactDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDeleteRequest.ProtoReflect.Descriptor instead.
func (*ContactDeleteRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{2}
}

func (x *ContactDeleteRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 联系人删除接口响应参数
type ContactDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactDeleteResponse) Reset() {
	*x = ContactDeleteResponse{}
	mi := &file_web_v1_contact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDeleteResponse) ProtoMessage() {}

func (x *ContactDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDeleteResponse.ProtoReflect.Descriptor instead.
func (*ContactDeleteResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{3}
}

// 联系人备注修改接口请求参数
type ContactEditRemarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactEditRemarkRequest) Reset() {
	*x = ContactEditRemarkRequest{}
	mi := &file_web_v1_contact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactEditRemarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactEditRemarkRequest) ProtoMessage() {}

func (x *ContactEditRemarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactEditRemarkRequest.ProtoReflect.Descriptor instead.
func (*ContactEditRemarkRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{4}
}

func (x *ContactEditRemarkRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactEditRemarkRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 联系人备注修改接口响应参数
type ContactEditRemarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactEditRemarkResponse) Reset() {
	*x = ContactEditRemarkResponse{}
	mi := &file_web_v1_contact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactEditRemarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactEditRemarkResponse) ProtoMessage() {}

func (x *ContactEditRemarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactEditRemarkResponse.ProtoReflect.Descriptor instead.
func (*ContactEditRemarkResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{5}
}

// 联系人详情接口请求参数
type ContactDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactDetailRequest) Reset() {
	*x = ContactDetailRequest{}
	mi := &file_web_v1_contact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDetailRequest) ProtoMessage() {}

func (x *ContactDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDetailRequest.ProtoReflect.Descriptor instead.
func (*ContactDetailRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{6}
}

func (x *ContactDetailRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 联系人详情接口响应参数
type ContactDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile         string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar         string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender         int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Motto          string                 `protobuf:"bytes,7,opt,name=motto,proto3" json:"motto,omitempty"`
	Email          string                 `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Relation       int32                  `protobuf:"varint,9,opt,name=relation,proto3" json:"relation,omitempty"` // 关系 1陌生人 2好友 3企业同事 4本人
	ContactRemark  string                 `protobuf:"bytes,10,opt,name=contact_remark,json=contactRemark,proto3" json:"contact_remark,omitempty"`
	ContactGroupId int32                  `protobuf:"varint,12,opt,name=contact_group_id,json=contactGroupId,proto3" json:"contact_group_id,omitempty"`
	OnlineStatus   string                 `protobuf:"bytes,13,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"` // Y:在线 N:离线
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContactDetailResponse) Reset() {
	*x = ContactDetailResponse{}
	mi := &file_web_v1_contact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDetailResponse) ProtoMessage() {}

func (x *ContactDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDetailResponse.ProtoReflect.Descriptor instead.
func (*ContactDetailResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{7}
}

func (x *ContactDetailResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactDetailResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ContactDetailResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactDetailResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactDetailResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactDetailResponse) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *ContactDetailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactDetailResponse) GetRelation() int32 {
	if x != nil {
		return x.Relation
	}
	return 0
}

func (x *ContactDetailResponse) GetContactRemark() string {
	if x != nil {
		return x.ContactRemark
	}
	return ""
}

func (x *ContactDetailResponse) GetContactGroupId() int32 {
	if x != nil {
		return x.ContactGroupId
	}
	return 0
}

func (x *ContactDetailResponse) GetOnlineStatus() string {
	if x != nil {
		return x.OnlineStatus
	}
	return ""
}

// 联系人搜索接口请求参数
type ContactSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactSearchRequest) Reset() {
	*x = ContactSearchRequest{}
	mi := &file_web_v1_contact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactSearchRequest) ProtoMessage() {}

func (x *ContactSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactSearchRequest.ProtoReflect.Descriptor instead.
func (*ContactSearchRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{8}
}

func (x *ContactSearchRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

// 联系人搜索接口响应参数
type ContactSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Motto         string                 `protobuf:"bytes,7,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactSearchResponse) Reset() {
	*x = ContactSearchResponse{}
	mi := &file_web_v1_contact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactSearchResponse) ProtoMessage() {}

func (x *ContactSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactSearchResponse.ProtoReflect.Descriptor instead.
func (*ContactSearchResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{9}
}

func (x *ContactSearchResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactSearchResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ContactSearchResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactSearchResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactSearchResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactSearchResponse) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

// 修改联系人分组接口请求参数
type ContactChangeGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactChangeGroupRequest) Reset() {
	*x = ContactChangeGroupRequest{}
	mi := &file_web_v1_contact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactChangeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactChangeGroupRequest) ProtoMessage() {}

func (x *ContactChangeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactChangeGroupRequest.ProtoReflect.Descriptor instead.
func (*ContactChangeGroupRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{10}
}

func (x *ContactChangeGroupRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactChangeGroupRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 修改联系人分组接口响应参数
type ContactChangeGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactChangeGroupResponse) Reset() {
	*x = ContactChangeGroupResponse{}
	mi := &file_web_v1_contact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactChangeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactChangeGroupResponse) ProtoMessage() {}

func (x *ContactChangeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactChangeGroupResponse.ProtoReflect.Descriptor instead.
func (*ContactChangeGroupResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{11}
}

// 获取联系人在线状态请求参数
type ContactOnlineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactOnlineStatusRequest) Reset() {
	*x = ContactOnlineStatusRequest{}
	mi := &file_web_v1_contact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactOnlineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactOnlineStatusRequest) ProtoMessage() {}

func (x *ContactOnlineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactOnlineStatusRequest.ProtoReflect.Descriptor instead.
func (*ContactOnlineStatusRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{12}
}

func (x *ContactOnlineStatusRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取联系人在线状态响应参数
type ContactOnlineStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 在线状态 [N:离线;Y:在线;]
	OnlineStatus  string `protobuf:"bytes,1,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactOnlineStatusResponse) Reset() {
	*x = ContactOnlineStatusResponse{}
	mi := &file_web_v1_contact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactOnlineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactOnlineStatusResponse) ProtoMessage() {}

func (x *ContactOnlineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactOnlineStatusResponse.ProtoReflect.Descriptor instead.
func (*ContactOnlineStatusResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{13}
}

func (x *ContactOnlineStatusResponse) GetOnlineStatus() string {
	if x != nil {
		return x.OnlineStatus
	}
	return ""
}

type ContactListResponse_Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 性别[0:未知;1:男;2:女;]
	Gender int32 `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	// 座右铭
	Motto string `protobuf:"bytes,4,opt,name=motto,proto3" json:"motto,omitempty"`
	// 头像
	Avatar string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 备注
	Remark string `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	// 联系人分组ID
	GroupId       int32 `protobuf:"varint,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactListResponse_Item) Reset() {
	*x = ContactListResponse_Item{}
	mi := &file_web_v1_contact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListResponse_Item) ProtoMessage() {}

func (x *ContactListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ContactListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactListResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactListResponse_Item) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactListResponse_Item) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *ContactListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactListResponse_Item) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ContactListResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

var File_web_v1_contact_proto protoreflect.FileDescriptor

const file_web_v1_contact_proto_rawDesc = "" +
	"\n" +
	"\x14web/v1/contact.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x14\n" +
	"\x12ContactListRequest\"\xb1\x02\n" +
	"\x13ContactListResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.web.ContactListResponse.ItemB\x04\xe2A\x01\x02R\x05items\x1a\xde\x01\n" +
	"\x04Item\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x06userId\x12 \n" +
	"\bnickname\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\bnickname\x12\x1c\n" +
	"\x06gender\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\x06gender\x12\x1a\n" +
	"\x05motto\x18\x04 \x01(\tB\x04\xe2A\x01\x02R\x05motto\x12\x1c\n" +
	"\x06avatar\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12\x1c\n" +
	"\x06remark\x18\a \x01(\tB\x04\xe2A\x01\x02R\x06remark\x12\x1f\n" +
	"\bgroup_id\x18\b \x01(\x05B\x04\xe2A\x01\x02R\agroupId\"<\n" +
	"\x14ContactDeleteRequest\x12$\n" +
	"\auser_id\x18\x01 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\x06userId\"\x17\n" +
	"\x15ContactDeleteResponse\"X\n" +
	"\x18ContactEditRemarkRequest\x12$\n" +
	"\auser_id\x18\x01 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\x06userId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\"\x1b\n" +
	"\x19ContactEditRemarkResponse\"<\n" +
	"\x14ContactDetailRequest\x12$\n" +
	"\auser_id\x18\x01 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\x06userId\"\x94\x03\n" +
	"\x15ContactDetailResponse\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x06userId\x12\x1c\n" +
	"\x06mobile\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x06mobile\x12 \n" +
	"\bnickname\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\bnickname\x12\x1c\n" +
	"\x06avatar\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12\x1c\n" +
	"\x06gender\x18\x06 \x01(\x05B\x04\xe2A\x01\x02R\x06gender\x12\x1a\n" +
	"\x05motto\x18\a \x01(\tB\x04\xe2A\x01\x02R\x05motto\x12\x1a\n" +
	"\x05email\x18\v \x01(\tB\x04\xe2A\x01\x02R\x05email\x12 \n" +
	"\brelation\x18\t \x01(\x05B\x04\xe2A\x01\x02R\brelation\x12+\n" +
	"\x0econtact_remark\x18\n" +
	" \x01(\tB\x04\xe2A\x01\x02R\rcontactRemark\x12.\n" +
	"\x10contact_group_id\x18\f \x01(\x05B\x04\xe2A\x01\x02R\x0econtactGroupId\x12)\n" +
	"\ronline_status\x18\r \x01(\tB\x04\xe2A\x01\x02R\fonlineStatus\";\n" +
	"\x14ContactSearchRequest\x12#\n" +
	"\x06mobile\x18\x02 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\x06mobile\"\xce\x01\n" +
	"\x15ContactSearchResponse\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x06userId\x12\x1c\n" +
	"\x06mobile\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x06mobile\x12 \n" +
	"\bnickname\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\bnickname\x12\x1c\n" +
	"\x06avatar\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12\x1c\n" +
	"\x06gender\x18\x06 \x01(\x05B\x04\xe2A\x01\x02R\x06gender\x12\x1a\n" +
	"\x05motto\x18\a \x01(\tB\x04\xe2A\x01\x02R\x05motto\"\\\n" +
	"\x19ContactChangeGroupRequest\x12$\n" +
	"\auser_id\x18\x01 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\"\x1c\n" +
	"\x1aContactChangeGroupResponse\"B\n" +
	"\x1aContactOnlineStatusRequest\x12$\n" +
	"\auser_id\x18\x01 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\x06userId\"H\n" +
	"\x1bContactOnlineStatusResponse\x12)\n" +
	"\ronline_status\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\fonlineStatus2\xfc\x05\n" +
	"\aContact\x12Z\n" +
	"\x04List\x12\x17.web.ContactListRequest\x1a\x18.web.ContactListResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/contact/list\x12b\n" +
	"\x06Delete\x12\x19.web.ContactDeleteRequest\x1a\x1a.web.ContactDeleteResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/contact/delete\x12s\n" +
	"\n" +
	"EditRemark\x12\x1d.web.ContactEditRemarkRequest\x1a\x1e.web.ContactEditRemarkResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/contact/edit-remark\x12b\n" +
	"\x06Detail\x12\x19.web.ContactDetailRequest\x1a\x1a.web.ContactDetailResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/contact/detail\x12b\n" +
	"\x06Search\x12\x19.web.ContactSearchRequest\x1a\x1a.web.ContactSearchResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/contact/search\x12w\n" +
	"\vChangeGroup\x12\x1e.web.ContactChangeGroupRequest\x1a\x1f.web.ContactChangeGroupResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/contact/change-group\x12{\n" +
	"\fOnlineStatus\x12\x1f.web.ContactOnlineStatusRequest\x1a .web.ContactOnlineStatusResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/contact/online-statusB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_contact_proto_rawDescOnce sync.Once
	file_web_v1_contact_proto_rawDescData []byte
)

func file_web_v1_contact_proto_rawDescGZIP() []byte {
	file_web_v1_contact_proto_rawDescOnce.Do(func() {
		file_web_v1_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_contact_proto_rawDesc), len(file_web_v1_contact_proto_rawDesc)))
	})
	return file_web_v1_contact_proto_rawDescData
}

var file_web_v1_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_web_v1_contact_proto_goTypes = []any{
	(*ContactListRequest)(nil),          // 0: web.ContactListRequest
	(*ContactListResponse)(nil),         // 1: web.ContactListResponse
	(*ContactDeleteRequest)(nil),        // 2: web.ContactDeleteRequest
	(*ContactDeleteResponse)(nil),       // 3: web.ContactDeleteResponse
	(*ContactEditRemarkRequest)(nil),    // 4: web.ContactEditRemarkRequest
	(*ContactEditRemarkResponse)(nil),   // 5: web.ContactEditRemarkResponse
	(*ContactDetailRequest)(nil),        // 6: web.ContactDetailRequest
	(*ContactDetailResponse)(nil),       // 7: web.ContactDetailResponse
	(*ContactSearchRequest)(nil),        // 8: web.ContactSearchRequest
	(*ContactSearchResponse)(nil),       // 9: web.ContactSearchResponse
	(*ContactChangeGroupRequest)(nil),   // 10: web.ContactChangeGroupRequest
	(*ContactChangeGroupResponse)(nil),  // 11: web.ContactChangeGroupResponse
	(*ContactOnlineStatusRequest)(nil),  // 12: web.ContactOnlineStatusRequest
	(*ContactOnlineStatusResponse)(nil), // 13: web.ContactOnlineStatusResponse
	(*ContactListResponse_Item)(nil),    // 14: web.ContactListResponse.Item
}
var file_web_v1_contact_proto_depIdxs = []int32{
	14, // 0: web.ContactListResponse.items:type_name -> web.ContactListResponse.Item
	0,  // 1: web.Contact.List:input_type -> web.ContactListRequest
	2,  // 2: web.Contact.Delete:input_type -> web.ContactDeleteRequest
	4,  // 3: web.Contact.EditRemark:input_type -> web.ContactEditRemarkRequest
	6,  // 4: web.Contact.Detail:input_type -> web.ContactDetailRequest
	8,  // 5: web.Contact.Search:input_type -> web.ContactSearchRequest
	10, // 6: web.Contact.ChangeGroup:input_type -> web.ContactChangeGroupRequest
	12, // 7: web.Contact.OnlineStatus:input_type -> web.ContactOnlineStatusRequest
	1,  // 8: web.Contact.List:output_type -> web.ContactListResponse
	3,  // 9: web.Contact.Delete:output_type -> web.ContactDeleteResponse
	5,  // 10: web.Contact.EditRemark:output_type -> web.ContactEditRemarkResponse
	7,  // 11: web.Contact.Detail:output_type -> web.ContactDetailResponse
	9,  // 12: web.Contact.Search:output_type -> web.ContactSearchResponse
	11, // 13: web.Contact.ChangeGroup:output_type -> web.ContactChangeGroupResponse
	13, // 14: web.Contact.OnlineStatus:output_type -> web.ContactOnlineStatusResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_web_v1_contact_proto_init() }
func file_web_v1_contact_proto_init() {
	if File_web_v1_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_contact_proto_rawDesc), len(file_web_v1_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_contact_proto_goTypes,
		DependencyIndexes: file_web_v1_contact_proto_depIdxs,
		MessageInfos:      file_web_v1_contact_proto_msgTypes,
	}.Build()
	File_web_v1_contact_proto = out.File
	file_web_v1_contact_proto_goTypes = nil
	file_web_v1_contact_proto_depIdxs = nil
}
