// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: web/v1/contact_apply.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加联系人申请接口请求参数
type ContactApplyCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyCreateRequest) Reset() {
	*x = ContactApplyCreateRequest{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyCreateRequest) ProtoMessage() {}

func (x *ContactApplyCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyCreateRequest.ProtoReflect.Descriptor instead.
func (*ContactApplyCreateRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{0}
}

func (x *ContactApplyCreateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactApplyCreateRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 添加联系人申请接口响应参数
type ContactApplyCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyCreateResponse) Reset() {
	*x = ContactApplyCreateResponse{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyCreateResponse) ProtoMessage() {}

func (x *ContactApplyCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyCreateResponse.ProtoReflect.Descriptor instead.
func (*ContactApplyCreateResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{1}
}

// 同意联系人申请接口请求参数
type ContactApplyAcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int32                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyAcceptRequest) Reset() {
	*x = ContactApplyAcceptRequest{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyAcceptRequest) ProtoMessage() {}

func (x *ContactApplyAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyAcceptRequest.ProtoReflect.Descriptor instead.
func (*ContactApplyAcceptRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{2}
}

func (x *ContactApplyAcceptRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *ContactApplyAcceptRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 同意联系人申请接口响应参数
type ContactApplyAcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyAcceptResponse) Reset() {
	*x = ContactApplyAcceptResponse{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyAcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyAcceptResponse) ProtoMessage() {}

func (x *ContactApplyAcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyAcceptResponse.ProtoReflect.Descriptor instead.
func (*ContactApplyAcceptResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{3}
}

// 拒绝联系人申请接口请求参数
type ContactApplyDeclineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int32                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyDeclineRequest) Reset() {
	*x = ContactApplyDeclineRequest{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyDeclineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyDeclineRequest) ProtoMessage() {}

func (x *ContactApplyDeclineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyDeclineRequest.ProtoReflect.Descriptor instead.
func (*ContactApplyDeclineRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{4}
}

func (x *ContactApplyDeclineRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *ContactApplyDeclineRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 拒绝联系人申请接口响应参数
type ContactApplyDeclineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyDeclineResponse) Reset() {
	*x = ContactApplyDeclineResponse{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyDeclineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyDeclineResponse) ProtoMessage() {}

func (x *ContactApplyDeclineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyDeclineResponse.ProtoReflect.Descriptor instead.
func (*ContactApplyDeclineResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{5}
}

// 联系人申请列表接口请求参数
type ContactApplyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyListRequest) Reset() {
	*x = ContactApplyListRequest{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyListRequest) ProtoMessage() {}

func (x *ContactApplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyListRequest.ProtoReflect.Descriptor instead.
func (*ContactApplyListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{6}
}

// 联系人申请列表接口响应参数
type ContactApplyListResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*ContactApplyListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyListResponse) Reset() {
	*x = ContactApplyListResponse{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyListResponse) ProtoMessage() {}

func (x *ContactApplyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyListResponse.ProtoReflect.Descriptor instead.
func (*ContactApplyListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{7}
}

func (x *ContactApplyListResponse) GetItems() []*ContactApplyListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContactApplyUnreadNumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyUnreadNumRequest) Reset() {
	*x = ContactApplyUnreadNumRequest{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyUnreadNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyUnreadNumRequest) ProtoMessage() {}

func (x *ContactApplyUnreadNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyUnreadNumRequest.ProtoReflect.Descriptor instead.
func (*ContactApplyUnreadNumRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{8}
}

type ContactApplyUnreadNumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyUnreadNumResponse) Reset() {
	*x = ContactApplyUnreadNumResponse{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyUnreadNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyUnreadNumResponse) ProtoMessage() {}

func (x *ContactApplyUnreadNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyUnreadNumResponse.ProtoReflect.Descriptor instead.
func (*ContactApplyUnreadNumResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{9}
}

func (x *ContactApplyUnreadNumResponse) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ContactApplyListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int32                  `protobuf:"varint,3,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyListResponse_Item) Reset() {
	*x = ContactApplyListResponse_Item{}
	mi := &file_web_v1_contact_apply_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyListResponse_Item) ProtoMessage() {}

func (x *ContactApplyListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_apply_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactApplyListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_apply_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ContactApplyListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactApplyListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactApplyListResponse_Item) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ContactApplyListResponse_Item) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ContactApplyListResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactApplyListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactApplyListResponse_Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_web_v1_contact_apply_proto protoreflect.FileDescriptor

const file_web_v1_contact_apply_proto_rawDesc = "" +
	"\n" +
	"\x1aweb/v1/contact_apply.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"^\n" +
	"\x19ContactApplyCreateRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x06userId\x12\x1f\n" +
	"\x06remark\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06remark\"\x1c\n" +
	"\x1aContactApplyCreateResponse\"`\n" +
	"\x19ContactApplyAcceptRequest\x12\"\n" +
	"\bapply_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\aapplyId\x12\x1f\n" +
	"\x06remark\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06remark\"\x1c\n" +
	"\x1aContactApplyAcceptResponse\"a\n" +
	"\x1aContactApplyDeclineRequest\x12\"\n" +
	"\bapply_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\aapplyId\x12\x1f\n" +
	"\x06remark\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06remark\"\x1d\n" +
	"\x1bContactApplyDeclineResponse\"\x19\n" +
	"\x17ContactApplyListRequest\"\xbe\x02\n" +
	"\x18ContactApplyListResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2\".web.ContactApplyListResponse.ItemB\x04\xe2A\x01\x02R\x05items\x1a\xe1\x01\n" +
	"\x04Item\x12\x14\n" +
	"\x02id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x02id\x12\x1d\n" +
	"\auser_id\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\x06userId\x12!\n" +
	"\tfriend_id\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\bfriendId\x12\x1c\n" +
	"\x06remark\x18\x04 \x01(\tB\x04\xe2A\x01\x02R\x06remark\x12 \n" +
	"\bnickname\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\bnickname\x12\x1c\n" +
	"\x06avatar\x18\x06 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12#\n" +
	"\n" +
	"created_at\x18\a \x01(\tB\x04\xe2A\x01\x02R\tcreatedAt\"\x1e\n" +
	"\x1cContactApplyUnreadNumRequest\"7\n" +
	"\x1dContactApplyUnreadNumResponse\x12\x16\n" +
	"\x03num\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x03num2\xdb\x04\n" +
	"\fContactApply\x12r\n" +
	"\x06Create\x12\x1e.web.ContactApplyCreateRequest\x1a\x1f.web.ContactApplyCreateResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/contact-apply/create\x12r\n" +
	"\x06Accept\x12\x1e.web.ContactApplyAcceptRequest\x1a\x1f.web.ContactApplyAcceptResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/contact-apply/accept\x12v\n" +
	"\aDecline\x12\x1f.web.ContactApplyDeclineRequest\x1a .web.ContactApplyDeclineResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/contact-apply/decline\x12j\n" +
	"\x04List\x12\x1c.web.ContactApplyListRequest\x1a\x1d.web.ContactApplyListResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/contact-apply/list\x12\x7f\n" +
	"\tUnreadNum\x12!.web.ContactApplyUnreadNumRequest\x1a\".web.ContactApplyUnreadNumResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/contact-apply/unread-numB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_contact_apply_proto_rawDescOnce sync.Once
	file_web_v1_contact_apply_proto_rawDescData []byte
)

func file_web_v1_contact_apply_proto_rawDescGZIP() []byte {
	file_web_v1_contact_apply_proto_rawDescOnce.Do(func() {
		file_web_v1_contact_apply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_contact_apply_proto_rawDesc), len(file_web_v1_contact_apply_proto_rawDesc)))
	})
	return file_web_v1_contact_apply_proto_rawDescData
}

var file_web_v1_contact_apply_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_web_v1_contact_apply_proto_goTypes = []any{
	(*ContactApplyCreateRequest)(nil),     // 0: web.ContactApplyCreateRequest
	(*ContactApplyCreateResponse)(nil),    // 1: web.ContactApplyCreateResponse
	(*ContactApplyAcceptRequest)(nil),     // 2: web.ContactApplyAcceptRequest
	(*ContactApplyAcceptResponse)(nil),    // 3: web.ContactApplyAcceptResponse
	(*ContactApplyDeclineRequest)(nil),    // 4: web.ContactApplyDeclineRequest
	(*ContactApplyDeclineResponse)(nil),   // 5: web.ContactApplyDeclineResponse
	(*ContactApplyListRequest)(nil),       // 6: web.ContactApplyListRequest
	(*ContactApplyListResponse)(nil),      // 7: web.ContactApplyListResponse
	(*ContactApplyUnreadNumRequest)(nil),  // 8: web.ContactApplyUnreadNumRequest
	(*ContactApplyUnreadNumResponse)(nil), // 9: web.ContactApplyUnreadNumResponse
	(*ContactApplyListResponse_Item)(nil), // 10: web.ContactApplyListResponse.Item
}
var file_web_v1_contact_apply_proto_depIdxs = []int32{
	10, // 0: web.ContactApplyListResponse.items:type_name -> web.ContactApplyListResponse.Item
	0,  // 1: web.ContactApply.Create:input_type -> web.ContactApplyCreateRequest
	2,  // 2: web.ContactApply.Accept:input_type -> web.ContactApplyAcceptRequest
	4,  // 3: web.ContactApply.Decline:input_type -> web.ContactApplyDeclineRequest
	6,  // 4: web.ContactApply.List:input_type -> web.ContactApplyListRequest
	8,  // 5: web.ContactApply.UnreadNum:input_type -> web.ContactApplyUnreadNumRequest
	1,  // 6: web.ContactApply.Create:output_type -> web.ContactApplyCreateResponse
	3,  // 7: web.ContactApply.Accept:output_type -> web.ContactApplyAcceptResponse
	5,  // 8: web.ContactApply.Decline:output_type -> web.ContactApplyDeclineResponse
	7,  // 9: web.ContactApply.List:output_type -> web.ContactApplyListResponse
	9,  // 10: web.ContactApply.UnreadNum:output_type -> web.ContactApplyUnreadNumResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_web_v1_contact_apply_proto_init() }
func file_web_v1_contact_apply_proto_init() {
	if File_web_v1_contact_apply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_contact_apply_proto_rawDesc), len(file_web_v1_contact_apply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_contact_apply_proto_goTypes,
		DependencyIndexes: file_web_v1_contact_apply_proto_depIdxs,
		MessageInfos:      file_web_v1_contact_apply_proto_msgTypes,
	}.Build()
	File_web_v1_contact_apply_proto = out.File
	file_web_v1_contact_apply_proto_goTypes = nil
	file_web_v1_contact_apply_proto_depIdxs = nil
}
