// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: web/v1/contact_group.proto

package web

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 联系人分组列表接口请求参数
type ContactGroupListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactGroupListRequest) Reset() {
	*x = ContactGroupListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_contact_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactGroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupListRequest) ProtoMessage() {}

func (x *ContactGroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupListRequest.ProtoReflect.Descriptor instead.
func (*ContactGroupListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_group_proto_rawDescGZIP(), []int{0}
}

// 联系人分组列表接口响应参数
type ContactGroupListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 分组列表
	Items []*ContactGroupListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ContactGroupListResponse) Reset() {
	*x = ContactGroupListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_contact_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactGroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupListResponse) ProtoMessage() {}

func (x *ContactGroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupListResponse.ProtoReflect.Descriptor instead.
func (*ContactGroupListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_group_proto_rawDescGZIP(), []int{1}
}

func (x *ContactGroupListResponse) GetItems() []*ContactGroupListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContactGroupSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ContactGroupSaveRequest_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ContactGroupSaveRequest) Reset() {
	*x = ContactGroupSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_contact_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactGroupSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupSaveRequest) ProtoMessage() {}

func (x *ContactGroupSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupSaveRequest.ProtoReflect.Descriptor instead.
func (*ContactGroupSaveRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_group_proto_rawDescGZIP(), []int{2}
}

func (x *ContactGroupSaveRequest) GetItems() []*ContactGroupSaveRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContactGroupSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactGroupSaveResponse) Reset() {
	*x = ContactGroupSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_contact_group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactGroupSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupSaveResponse) ProtoMessage() {}

func (x *ContactGroupSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupSaveResponse.ProtoReflect.Descriptor instead.
func (*ContactGroupSaveResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_group_proto_rawDescGZIP(), []int{3}
}

type ContactGroupListResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 分组ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分组名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 联系人数
	Count int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// 分组排序
	Sort int32 `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *ContactGroupListResponse_Item) Reset() {
	*x = ContactGroupListResponse_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_contact_group_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactGroupListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupListResponse_Item) ProtoMessage() {}

func (x *ContactGroupListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_group_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactGroupListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_group_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ContactGroupListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactGroupListResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactGroupListResponse_Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContactGroupListResponse_Item) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ContactGroupSaveRequest_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sort int32  `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ContactGroupSaveRequest_Item) Reset() {
	*x = ContactGroupSaveRequest_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_contact_group_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactGroupSaveRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupSaveRequest_Item) ProtoMessage() {}

func (x *ContactGroupSaveRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_contact_group_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupSaveRequest_Item.ProtoReflect.Descriptor instead.
func (*ContactGroupSaveRequest_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_contact_group_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ContactGroupSaveRequest_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactGroupSaveRequest_Item) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ContactGroupSaveRequest_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_web_v1_contact_group_proto protoreflect.FileDescriptor

var file_web_v1_contact_group_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x77, 0x65, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x77, 0x65,
	0x62, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xaa, 0x01, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x54, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x22, 0xad, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x59, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x1a, 0x02, 0x28, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x20, 0x00, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c,
	0x5a, 0x0a, 0x77, 0x65, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x65, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web_v1_contact_group_proto_rawDescOnce sync.Once
	file_web_v1_contact_group_proto_rawDescData = file_web_v1_contact_group_proto_rawDesc
)

func file_web_v1_contact_group_proto_rawDescGZIP() []byte {
	file_web_v1_contact_group_proto_rawDescOnce.Do(func() {
		file_web_v1_contact_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_v1_contact_group_proto_rawDescData)
	})
	return file_web_v1_contact_group_proto_rawDescData
}

var file_web_v1_contact_group_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_web_v1_contact_group_proto_goTypes = []any{
	(*ContactGroupListRequest)(nil),       // 0: web.ContactGroupListRequest
	(*ContactGroupListResponse)(nil),      // 1: web.ContactGroupListResponse
	(*ContactGroupSaveRequest)(nil),       // 2: web.ContactGroupSaveRequest
	(*ContactGroupSaveResponse)(nil),      // 3: web.ContactGroupSaveResponse
	(*ContactGroupListResponse_Item)(nil), // 4: web.ContactGroupListResponse.Item
	(*ContactGroupSaveRequest_Item)(nil),  // 5: web.ContactGroupSaveRequest.Item
}
var file_web_v1_contact_group_proto_depIdxs = []int32{
	4, // 0: web.ContactGroupListResponse.items:type_name -> web.ContactGroupListResponse.Item
	5, // 1: web.ContactGroupSaveRequest.items:type_name -> web.ContactGroupSaveRequest.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_web_v1_contact_group_proto_init() }
func file_web_v1_contact_group_proto_init() {
	if File_web_v1_contact_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web_v1_contact_group_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ContactGroupListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_contact_group_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ContactGroupListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_contact_group_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ContactGroupSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_contact_group_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ContactGroupSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_contact_group_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ContactGroupListResponse_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_contact_group_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ContactGroupSaveRequest_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_v1_contact_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_v1_contact_group_proto_goTypes,
		DependencyIndexes: file_web_v1_contact_group_proto_depIdxs,
		MessageInfos:      file_web_v1_contact_group_proto_msgTypes,
	}.Build()
	File_web_v1_contact_group_proto = out.File
	file_web_v1_contact_group_proto_rawDesc = nil
	file_web_v1_contact_group_proto_goTypes = nil
	file_web_v1_contact_group_proto_depIdxs = nil
}
