// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IContactGroupHandler BFF 接口
type IContactGroupHandler interface {

	// 联系人分组列表接口
	List(ctx context.Context, in *ContactGroupListRequest) (*ContactGroupListResponse, error)
	// 保存联系人分组接口
	Save(ctx context.Context, in *ContactGroupSaveRequest) (*ContactGroupSaveResponse, error)
}

// RegisterContactGroupHandler 注册服务路由处理器
func RegisterContactGroupHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler IContactGroupHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/contact-group/list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ContactGroupListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.List(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/contact-group/save", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in ContactGroupSaveRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Save(ctx.Request.Context(), &in)
	}))

}
