// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IGroupVoteHandler BFF 接口
type IGroupVoteHandler interface {

	// 创建群组投票接口
	Create(ctx context.Context, in *GroupVoteCreateRequest) (*GroupVoteCreateResponse, error)
	// 提交群组投票接口
	Submit(ctx context.Context, in *GroupVoteSubmitRequest) (*GroupVoteSubmitResponse, error)
	// 获取群组投票详情接口
	Detail(ctx context.Context, in *GroupVoteDetailRequest) (*GroupVoteDetailResponse, error)
}

// RegisterGroupVoteHandler 注册服务路由处理器
func RegisterGroupVoteHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler IGroupVoteHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/group-vote/create", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupVoteCreateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Create(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group-vote/submit", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupVoteSubmitRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Submit(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group-vote/detail", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupVoteDetailRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Detail(ctx.Request.Context(), &in)
	}))

}
