// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: web/v1/group_apply.proto

package web

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建群组申请接口请求参数
type GroupApplyCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int32  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Remark  string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *GroupApplyCreateRequest) Reset() {
	*x = GroupApplyCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyCreateRequest) ProtoMessage() {}

func (x *GroupApplyCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyCreateRequest.ProtoReflect.Descriptor instead.
func (*GroupApplyCreateRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{0}
}

func (x *GroupApplyCreateRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupApplyCreateRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 创建群组申请接口响应参数
type GroupApplyCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupApplyCreateResponse) Reset() {
	*x = GroupApplyCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyCreateResponse) ProtoMessage() {}

func (x *GroupApplyCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyCreateResponse.ProtoReflect.Descriptor instead.
func (*GroupApplyCreateResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{1}
}

// 删除群组申请接口请求参数
type GroupApplyDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplyId int32 `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
}

func (x *GroupApplyDeleteRequest) Reset() {
	*x = GroupApplyDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyDeleteRequest) ProtoMessage() {}

func (x *GroupApplyDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyDeleteRequest.ProtoReflect.Descriptor instead.
func (*GroupApplyDeleteRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{2}
}

func (x *GroupApplyDeleteRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

// 删除群组申请接口响应参数
type GroupApplyDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupApplyDeleteResponse) Reset() {
	*x = GroupApplyDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyDeleteResponse) ProtoMessage() {}

func (x *GroupApplyDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyDeleteResponse.ProtoReflect.Descriptor instead.
func (*GroupApplyDeleteResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{3}
}

// 同意群组申请接口请求参数
type GroupApplyAgreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplyId int32 `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
}

func (x *GroupApplyAgreeRequest) Reset() {
	*x = GroupApplyAgreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyAgreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyAgreeRequest) ProtoMessage() {}

func (x *GroupApplyAgreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyAgreeRequest.ProtoReflect.Descriptor instead.
func (*GroupApplyAgreeRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{4}
}

func (x *GroupApplyAgreeRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

// 同意群组申请接口响应参数
type GroupApplyAgreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupApplyAgreeResponse) Reset() {
	*x = GroupApplyAgreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyAgreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyAgreeResponse) ProtoMessage() {}

func (x *GroupApplyAgreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyAgreeResponse.ProtoReflect.Descriptor instead.
func (*GroupApplyAgreeResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{5}
}

// 拒绝群组申请接口请求参数
type GroupApplyDeclineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplyId int32  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	Remark  string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *GroupApplyDeclineRequest) Reset() {
	*x = GroupApplyDeclineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyDeclineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyDeclineRequest) ProtoMessage() {}

func (x *GroupApplyDeclineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyDeclineRequest.ProtoReflect.Descriptor instead.
func (*GroupApplyDeclineRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{6}
}

func (x *GroupApplyDeclineRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *GroupApplyDeclineRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 拒绝群组申请接口响应参数
type GroupApplyDeclineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupApplyDeclineResponse) Reset() {
	*x = GroupApplyDeclineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyDeclineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyDeclineResponse) ProtoMessage() {}

func (x *GroupApplyDeclineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyDeclineResponse.ProtoReflect.Descriptor instead.
func (*GroupApplyDeclineResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{7}
}

// 群组申请列表接口请求参数
type GroupApplyListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int32 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *GroupApplyListRequest) Reset() {
	*x = GroupApplyListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyListRequest) ProtoMessage() {}

func (x *GroupApplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyListRequest.ProtoReflect.Descriptor instead.
func (*GroupApplyListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{8}
}

func (x *GroupApplyListRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 群组申请列表接口响应参数
type GroupApplyListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GroupApplyListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GroupApplyListResponse) Reset() {
	*x = GroupApplyListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyListResponse) ProtoMessage() {}

func (x *GroupApplyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyListResponse.ProtoReflect.Descriptor instead.
func (*GroupApplyListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{9}
}

func (x *GroupApplyListResponse) GetItems() []*GroupApplyListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 所有群组申请列表接口请求参数
type GroupApplyAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupApplyAllRequest) Reset() {
	*x = GroupApplyAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyAllRequest) ProtoMessage() {}

func (x *GroupApplyAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyAllRequest.ProtoReflect.Descriptor instead.
func (*GroupApplyAllRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{10}
}

// 所有群组申请列表接口响应参数
type GroupApplyAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GroupApplyAllResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GroupApplyAllResponse) Reset() {
	*x = GroupApplyAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyAllResponse) ProtoMessage() {}

func (x *GroupApplyAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyAllResponse.ProtoReflect.Descriptor instead.
func (*GroupApplyAllResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{11}
}

func (x *GroupApplyAllResponse) GetItems() []*GroupApplyAllResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupApplyUnreadNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupApplyUnreadNumRequest) Reset() {
	*x = GroupApplyUnreadNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyUnreadNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyUnreadNumRequest) ProtoMessage() {}

func (x *GroupApplyUnreadNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyUnreadNumRequest.ProtoReflect.Descriptor instead.
func (*GroupApplyUnreadNumRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{12}
}

type GroupApplyUnreadNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GroupApplyUnreadNumResponse) Reset() {
	*x = GroupApplyUnreadNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyUnreadNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyUnreadNumResponse) ProtoMessage() {}

func (x *GroupApplyUnreadNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyUnreadNumResponse.ProtoReflect.Descriptor instead.
func (*GroupApplyUnreadNumResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{13}
}

func (x *GroupApplyUnreadNumResponse) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GroupApplyListResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId   int32  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Remark    string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Avatar    string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname  string `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *GroupApplyListResponse_Item) Reset() {
	*x = GroupApplyListResponse_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyListResponse_Item) ProtoMessage() {}

func (x *GroupApplyListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyListResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupApplyListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GroupApplyListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupApplyListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupApplyListResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupApplyListResponse_Item) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GroupApplyListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupApplyListResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupApplyListResponse_Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GroupApplyAllResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId   int32  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName string `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Remark    string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Avatar    string `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname  string `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreatedAt string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *GroupApplyAllResponse_Item) Reset() {
	*x = GroupApplyAllResponse_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_v1_group_apply_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupApplyAllResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyAllResponse_Item) ProtoMessage() {}

func (x *GroupApplyAllResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_apply_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyAllResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupApplyAllResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_group_apply_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GroupApplyAllResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupApplyAllResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupApplyAllResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupApplyAllResponse_Item) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupApplyAllResponse_Item) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GroupApplyAllResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupApplyAllResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupApplyAllResponse_Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_web_v1_group_apply_proto protoreflect.FileDescriptor

var file_web_v1_group_apply_proto_rawDesc = []byte{
	0x0a, 0x18, 0x77, 0x65, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x61,
	0x70, 0x70, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x77, 0x65, 0x62, 0x1a,
	0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x17, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x01, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x3d, 0x0a, 0x17, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x08, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x01, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x79,
	0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3c,
	0x0a, 0x16, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x67, 0x72, 0x65,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x6c,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a,
	0x02, 0x28, 0x01, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x67, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5f, 0x0a, 0x18, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x01, 0x52, 0x07,
	0x61, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01,
	0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x15, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x01, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x22, 0xb2, 0x02, 0x0a, 0x16, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x77,
	0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xdf, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x12, 0x1c, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x12, 0x20, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xdb, 0x02, 0x0a, 0x15, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x84, 0x02, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x14, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x04, 0xe2, 0x41, 0x01,
	0x02, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x06, 0x72, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02,
	0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1c, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x20, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xe2, 0x41,
	0x01, 0x02, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x1c, 0x0a,
	0x1a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x55, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x1b, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x32, 0x87, 0x06, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x12, 0x6c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x77, 0x65,
	0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x65, 0x62, 0x2e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f,
	0x3a, 0x01, 0x2a, 0x22, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x6c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x77, 0x65, 0x62, 0x2e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x3a, 0x01,
	0x2a, 0x22, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2d, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x68, 0x0a,
	0x05, 0x41, 0x67, 0x72, 0x65, 0x65, 0x12, 0x1b, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x67, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x41, 0x67, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x61, 0x70, 0x70, 0x6c,
	0x79, 0x2f, 0x61, 0x67, 0x72, 0x65, 0x65, 0x12, 0x70, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x1d, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x3a, 0x01, 0x2a, 0x22, 0x1b, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x61, 0x70, 0x70, 0x6c,
	0x79, 0x2f, 0x64, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x64, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1a, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1d, 0x3a, 0x01, 0x2a, 0x22, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x60, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x12, 0x19, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x3a, 0x01, 0x2a, 0x22, 0x17, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x2f, 0x61, 0x6c,
	0x6c, 0x12, 0x79, 0x0a, 0x09, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x1f,
	0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x55,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x3a, 0x01, 0x2a, 0x22, 0x1e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x61, 0x70, 0x70, 0x6c,
	0x79, 0x2f, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x2d, 0x6e, 0x75, 0x6d, 0x42, 0x0c, 0x5a, 0x0a,
	0x77, 0x65, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x65, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_web_v1_group_apply_proto_rawDescOnce sync.Once
	file_web_v1_group_apply_proto_rawDescData = file_web_v1_group_apply_proto_rawDesc
)

func file_web_v1_group_apply_proto_rawDescGZIP() []byte {
	file_web_v1_group_apply_proto_rawDescOnce.Do(func() {
		file_web_v1_group_apply_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_v1_group_apply_proto_rawDescData)
	})
	return file_web_v1_group_apply_proto_rawDescData
}

var file_web_v1_group_apply_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_web_v1_group_apply_proto_goTypes = []any{
	(*GroupApplyCreateRequest)(nil),     // 0: web.GroupApplyCreateRequest
	(*GroupApplyCreateResponse)(nil),    // 1: web.GroupApplyCreateResponse
	(*GroupApplyDeleteRequest)(nil),     // 2: web.GroupApplyDeleteRequest
	(*GroupApplyDeleteResponse)(nil),    // 3: web.GroupApplyDeleteResponse
	(*GroupApplyAgreeRequest)(nil),      // 4: web.GroupApplyAgreeRequest
	(*GroupApplyAgreeResponse)(nil),     // 5: web.GroupApplyAgreeResponse
	(*GroupApplyDeclineRequest)(nil),    // 6: web.GroupApplyDeclineRequest
	(*GroupApplyDeclineResponse)(nil),   // 7: web.GroupApplyDeclineResponse
	(*GroupApplyListRequest)(nil),       // 8: web.GroupApplyListRequest
	(*GroupApplyListResponse)(nil),      // 9: web.GroupApplyListResponse
	(*GroupApplyAllRequest)(nil),        // 10: web.GroupApplyAllRequest
	(*GroupApplyAllResponse)(nil),       // 11: web.GroupApplyAllResponse
	(*GroupApplyUnreadNumRequest)(nil),  // 12: web.GroupApplyUnreadNumRequest
	(*GroupApplyUnreadNumResponse)(nil), // 13: web.GroupApplyUnreadNumResponse
	(*GroupApplyListResponse_Item)(nil), // 14: web.GroupApplyListResponse.Item
	(*GroupApplyAllResponse_Item)(nil),  // 15: web.GroupApplyAllResponse.Item
}
var file_web_v1_group_apply_proto_depIdxs = []int32{
	14, // 0: web.GroupApplyListResponse.items:type_name -> web.GroupApplyListResponse.Item
	15, // 1: web.GroupApplyAllResponse.items:type_name -> web.GroupApplyAllResponse.Item
	0,  // 2: web.GroupApply.Create:input_type -> web.GroupApplyCreateRequest
	2,  // 3: web.GroupApply.Delete:input_type -> web.GroupApplyDeleteRequest
	4,  // 4: web.GroupApply.Agree:input_type -> web.GroupApplyAgreeRequest
	6,  // 5: web.GroupApply.Decline:input_type -> web.GroupApplyDeclineRequest
	8,  // 6: web.GroupApply.List:input_type -> web.GroupApplyListRequest
	10, // 7: web.GroupApply.All:input_type -> web.GroupApplyAllRequest
	12, // 8: web.GroupApply.UnreadNum:input_type -> web.GroupApplyUnreadNumRequest
	1,  // 9: web.GroupApply.Create:output_type -> web.GroupApplyCreateResponse
	3,  // 10: web.GroupApply.Delete:output_type -> web.GroupApplyDeleteResponse
	5,  // 11: web.GroupApply.Agree:output_type -> web.GroupApplyAgreeResponse
	7,  // 12: web.GroupApply.Decline:output_type -> web.GroupApplyDeclineResponse
	9,  // 13: web.GroupApply.List:output_type -> web.GroupApplyListResponse
	11, // 14: web.GroupApply.All:output_type -> web.GroupApplyAllResponse
	13, // 15: web.GroupApply.UnreadNum:output_type -> web.GroupApplyUnreadNumResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_web_v1_group_apply_proto_init() }
func file_web_v1_group_apply_proto_init() {
	if File_web_v1_group_apply_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web_v1_group_apply_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyAgreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyAgreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyDeclineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyDeclineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyUnreadNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyUnreadNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyListResponse_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_v1_group_apply_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GroupApplyAllResponse_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_v1_group_apply_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_group_apply_proto_goTypes,
		DependencyIndexes: file_web_v1_group_apply_proto_depIdxs,
		MessageInfos:      file_web_v1_group_apply_proto_msgTypes,
	}.Build()
	File_web_v1_group_apply_proto = out.File
	file_web_v1_group_apply_proto_rawDesc = nil
	file_web_v1_group_apply_proto_goTypes = nil
	file_web_v1_group_apply_proto_depIdxs = nil
}
