// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IGroupHandler BFF 接口
type IGroupHandler interface {

	// 群列表接口
	List(ctx context.Context, in *GroupListRequest) (*GroupListResponse, error)
	// 创建群聊接口
	Create(ctx context.Context, in *GroupCreateRequest) (*GroupCreateResponse, error)
	// 群聊详情接口
	Detail(ctx context.Context, in *GroupDetailRequest) (*GroupDetailResponse, error)
	// 群成员列表接口
	MemberList(ctx context.Context, in *GroupMemberListRequest) (*GroupMemberListResponse, error)
	// 解散群聊接口
	Dismiss(ctx context.Context, in *GroupDismissRequest) (*GroupDismissResponse, error)
	// 邀请加入群聊接口
	Invite(ctx context.Context, in *GroupInviteRequest) (*GroupInviteResponse, error)
	// 获取可邀请好友列表接口
	GetInviteFriends(ctx context.Context, in *GetInviteFriendsRequest) (*GetInviteFriendsResponse, error)
	// 退出群聊接口
	Secede(ctx context.Context, in *GroupSecedeRequest) (*GroupSecedeResponse, error)
	// 设置群聊接口
	Setting(ctx context.Context, in *GroupSettingRequest) (*GroupSettingResponse, error)
	// 群聊名片更新接口
	RemarkUpdate(ctx context.Context, in *GroupRemarkUpdateRequest) (*GroupRemarkUpdateResponse, error)
	// 移出群成员接口
	RemoveMember(ctx context.Context, in *GroupRemoveMemberRequest) (*GroupRemoveMemberResponse, error)
	// 公开群聊列表接口
	OvertList(ctx context.Context, in *GroupOvertListRequest) (*GroupOvertListResponse, error)
	// 群主更换接口
	Handover(ctx context.Context, in *GroupHandoverRequest) (*GroupHandoverResponse, error)
	// 分配管理员接口
	AssignAdmin(ctx context.Context, in *GroupAssignAdminRequest) (*GroupAssignAdminResponse, error)
	// 群成员禁言接口
	NoSpeak(ctx context.Context, in *GroupNoSpeakRequest) (*GroupNoSpeakResponse, error)
	// 群禁言接口
	Mute(ctx context.Context, in *GroupMuteRequest) (*GroupMuteResponse, error)
	// 群公开修改接口
	Overt(ctx context.Context, in *GroupOvertRequest) (*GroupOvertResponse, error)
}

// RegisterGroupHandler 注册服务路由处理器
func RegisterGroupHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler IGroupHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/group/list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.List(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/create", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupCreateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Create(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/detail", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupDetailRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Detail(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/member-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupMemberListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MemberList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/dismiss", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupDismissRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Dismiss(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/invite", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupInviteRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Invite(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/get-invite-friends", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GetInviteFriendsRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.GetInviteFriends(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/secede", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupSecedeRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Secede(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/setting", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupSettingRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Setting(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/remark-update", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupRemarkUpdateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.RemarkUpdate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/remove-member", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupRemoveMemberRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.RemoveMember(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/overt-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupOvertListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.OvertList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/handover", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupHandoverRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Handover(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/assign-admin", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupAssignAdminRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.AssignAdmin(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/no-speak", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupNoSpeakRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.NoSpeak(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/mute", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupMuteRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Mute(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/group/overt", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in GroupOvertRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Overt(ctx.Request.Context(), &in)
	}))

}
