// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: web/v1/message.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TalkMode      int32                  `protobuf:"varint,1,opt,name=talk_mode,json=talkMode,proto3" json:"talk_mode,omitempty"`
	ToFromId      int32                  `protobuf:"varint,2,opt,name=to_from_id,json=toFromId,proto3" json:"to_from_id,omitempty"`
	MsgId         string                 `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRevokeRequest) Reset() {
	*x = MessageRevokeRequest{}
	mi := &file_web_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRevokeRequest) ProtoMessage() {}

func (x *MessageRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRevokeRequest.ProtoReflect.Descriptor instead.
func (*MessageRevokeRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRevokeRequest) GetTalkMode() int32 {
	if x != nil {
		return x.TalkMode
	}
	return 0
}

func (x *MessageRevokeRequest) GetToFromId() int32 {
	if x != nil {
		return x.ToFromId
	}
	return 0
}

func (x *MessageRevokeRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type MessageRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRevokeResponse) Reset() {
	*x = MessageRevokeResponse{}
	mi := &file_web_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRevokeResponse) ProtoMessage() {}

func (x *MessageRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRevokeResponse.ProtoReflect.Descriptor instead.
func (*MessageRevokeResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{1}
}

type MessageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TalkMode      int32                  `protobuf:"varint,1,opt,name=talk_mode,json=talkMode,proto3" json:"talk_mode,omitempty"`
	ToFromId      int32                  `protobuf:"varint,2,opt,name=to_from_id,json=toFromId,proto3" json:"to_from_id,omitempty"`
	MsgIds        []string               `protobuf:"bytes,3,rep,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeleteRequest) Reset() {
	*x = MessageDeleteRequest{}
	mi := &file_web_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeleteRequest) ProtoMessage() {}

func (x *MessageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeleteRequest.ProtoReflect.Descriptor instead.
func (*MessageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageDeleteRequest) GetTalkMode() int32 {
	if x != nil {
		return x.TalkMode
	}
	return 0
}

func (x *MessageDeleteRequest) GetToFromId() int32 {
	if x != nil {
		return x.ToFromId
	}
	return 0
}

func (x *MessageDeleteRequest) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

type MessageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeleteResponse) Reset() {
	*x = MessageDeleteResponse{}
	mi := &file_web_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeleteResponse) ProtoMessage() {}

func (x *MessageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeleteResponse.ProtoReflect.Descriptor instead.
func (*MessageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{3}
}

type MessageRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TalkMode      int32                  `protobuf:"varint,1,opt,name=talk_mode,json=talkMode,proto3" json:"talk_mode,omitempty"`
	ToFromId      int32                  `protobuf:"varint,2,opt,name=to_from_id,json=toFromId,proto3" json:"to_from_id,omitempty"`
	Cursor        int32                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRecordsRequest) Reset() {
	*x = MessageRecordsRequest{}
	mi := &file_web_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecordsRequest) ProtoMessage() {}

func (x *MessageRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecordsRequest.ProtoReflect.Descriptor instead.
func (*MessageRecordsRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageRecordsRequest) GetTalkMode() int32 {
	if x != nil {
		return x.TalkMode
	}
	return 0
}

func (x *MessageRecordsRequest) GetToFromId() int32 {
	if x != nil {
		return x.ToFromId
	}
	return 0
}

func (x *MessageRecordsRequest) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MessageRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MessageRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MessageRecord       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int32                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRecordsResponse) Reset() {
	*x = MessageRecordsResponse{}
	mi := &file_web_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecordsResponse) ProtoMessage() {}

func (x *MessageRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecordsResponse.ProtoReflect.Descriptor instead.
func (*MessageRecordsResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *MessageRecordsResponse) GetItems() []*MessageRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MessageRecordsResponse) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type MessageHistoryRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TalkMode      int32                  `protobuf:"varint,1,opt,name=talk_mode,json=talkMode,proto3" json:"talk_mode,omitempty"`
	ToFromId      int32                  `protobuf:"varint,2,opt,name=to_from_id,json=toFromId,proto3" json:"to_from_id,omitempty"`
	Cursor        int32                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	MsgType       int32                  `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHistoryRecordsRequest) Reset() {
	*x = MessageHistoryRecordsRequest{}
	mi := &file_web_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHistoryRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHistoryRecordsRequest) ProtoMessage() {}

func (x *MessageHistoryRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHistoryRecordsRequest.ProtoReflect.Descriptor instead.
func (*MessageHistoryRecordsRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageHistoryRecordsRequest) GetTalkMode() int32 {
	if x != nil {
		return x.TalkMode
	}
	return 0
}

func (x *MessageHistoryRecordsRequest) GetToFromId() int32 {
	if x != nil {
		return x.ToFromId
	}
	return 0
}

func (x *MessageHistoryRecordsRequest) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MessageHistoryRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MessageHistoryRecordsRequest) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

type MessageHistoryRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MessageRecord       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int32                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHistoryRecordsResponse) Reset() {
	*x = MessageHistoryRecordsResponse{}
	mi := &file_web_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHistoryRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHistoryRecordsResponse) ProtoMessage() {}

func (x *MessageHistoryRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHistoryRecordsResponse.ProtoReflect.Descriptor instead.
func (*MessageHistoryRecordsResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *MessageHistoryRecordsResponse) GetItems() []*MessageRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MessageHistoryRecordsResponse) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type MessageForwardRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TalkMode      int32                  `protobuf:"varint,1,opt,name=talk_mode,json=talkMode,proto3" json:"talk_mode,omitempty"`
	MsgIds        []string               `protobuf:"bytes,2,rep,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageForwardRecordsRequest) Reset() {
	*x = MessageForwardRecordsRequest{}
	mi := &file_web_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageForwardRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageForwardRecordsRequest) ProtoMessage() {}

func (x *MessageForwardRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageForwardRecordsRequest.ProtoReflect.Descriptor instead.
func (*MessageForwardRecordsRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *MessageForwardRecordsRequest) GetTalkMode() int32 {
	if x != nil {
		return x.TalkMode
	}
	return 0
}

func (x *MessageForwardRecordsRequest) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

type MessageRecordsClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MessageRecord       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRecordsClearResponse) Reset() {
	*x = MessageRecordsClearResponse{}
	mi := &file_web_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecordsClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecordsClearResponse) ProtoMessage() {}

func (x *MessageRecordsClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecordsClearResponse.ProtoReflect.Descriptor instead.
func (*MessageRecordsClearResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *MessageRecordsClearResponse) GetItems() []*MessageRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

type MessageRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MsgType       int32                  `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	FromId        int32                  `protobuf:"varint,4,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	IsRevoked     int32                  `protobuf:"varint,7,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	SendTime      string                 `protobuf:"bytes,9,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Extra         string                 `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`
	Quote         string                 `protobuf:"bytes,12,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRecord) Reset() {
	*x = MessageRecord{}
	mi := &file_web_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecord) ProtoMessage() {}

func (x *MessageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecord.ProtoReflect.Descriptor instead.
func (*MessageRecord) Descriptor() ([]byte, []int) {
	return file_web_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *MessageRecord) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MessageRecord) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MessageRecord) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MessageRecord) GetFromId() int32 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *MessageRecord) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *MessageRecord) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *MessageRecord) GetIsRevoked() int32 {
	if x != nil {
		return x.IsRevoked
	}
	return 0
}

func (x *MessageRecord) GetSendTime() string {
	if x != nil {
		return x.SendTime
	}
	return ""
}

func (x *MessageRecord) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *MessageRecord) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

var File_web_v1_message_proto protoreflect.FileDescriptor

const file_web_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x14web/v1/message.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x8f\x01\n" +
	"\x14MessageRevokeRequest\x12(\n" +
	"\ttalk_mode\x18\x01 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\btalkMode\x12)\n" +
	"\n" +
	"to_from_id\x18\x02 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\btoFromId\x12\"\n" +
	"\x06msg_id\x18\x03 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\x05msgId\"\x17\n" +
	"\x15MessageRevokeResponse\"\x92\x01\n" +
	"\x14MessageDeleteRequest\x12(\n" +
	"\ttalk_mode\x18\x01 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\btalkMode\x12)\n" +
	"\n" +
	"to_from_id\x18\x02 \x01(\x05B\v\xe2A\x01\x02\xbaH\x04\x1a\x02(\x01R\btoFromId\x12%\n" +
	"\amsg_ids\x18\x03 \x03(\tB\f\xe2A\x01\x02\xbaH\x05\x92\x01\x02\b\x01R\x06msgIds\"\x17\n" +
	"\x15MessageDeleteResponse\"\x98\x01\n" +
	"\x15MessageRecordsRequest\x12!\n" +
	"\ttalk_mode\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\btalkMode\x12\"\n" +
	"\n" +
	"to_from_id\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\btoFromId\x12\x1c\n" +
	"\x06cursor\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\x06cursor\x12\x1a\n" +
	"\x05limit\x18\x04 \x01(\x05B\x04\xe2A\x01\x02R\x05limit\"f\n" +
	"\x16MessageRecordsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x12.web.MessageRecordB\x04\xe2A\x01\x02R\x05items\x12\x1c\n" +
	"\x06cursor\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\x06cursor\"\xc0\x01\n" +
	"\x1cMessageHistoryRecordsRequest\x12!\n" +
	"\ttalk_mode\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\btalkMode\x12\"\n" +
	"\n" +
	"to_from_id\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\btoFromId\x12\x1c\n" +
	"\x06cursor\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\x06cursor\x12\x1a\n" +
	"\x05limit\x18\x04 \x01(\x05B\x04\xe2A\x01\x02R\x05limit\x12\x1f\n" +
	"\bmsg_type\x18\x05 \x01(\x05B\x04\xe2A\x01\x02R\amsgType\"m\n" +
	"\x1dMessageHistoryRecordsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x12.web.MessageRecordB\x04\xe2A\x01\x02R\x05items\x12\x1c\n" +
	"\x06cursor\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\x06cursor\"T\n" +
	"\x1cMessageForwardRecordsRequest\x12\x1b\n" +
	"\ttalk_mode\x18\x01 \x01(\x05R\btalkMode\x12\x17\n" +
	"\amsg_ids\x18\x02 \x03(\tR\x06msgIds\"M\n" +
	"\x1bMessageRecordsClearResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x12.web.MessageRecordB\x04\xe2A\x01\x02R\x05items\"\xce\x02\n" +
	"\rMessageRecord\x12\x1b\n" +
	"\x06msg_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x05msgId\x12 \n" +
	"\bsequence\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\bsequence\x12\x1f\n" +
	"\bmsg_type\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\amsgType\x12\x1d\n" +
	"\afrom_id\x18\x04 \x01(\x05B\x04\xe2A\x01\x02R\x06fromId\x12 \n" +
	"\bnickname\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\bnickname\x12\x1c\n" +
	"\x06avatar\x18\x06 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12#\n" +
	"\n" +
	"is_revoked\x18\a \x01(\x05B\x04\xe2A\x01\x02R\tisRevoked\x12!\n" +
	"\tsend_time\x18\t \x01(\tB\x04\xe2A\x01\x02R\bsendTime\x12\x1a\n" +
	"\x05extra\x18\n" +
	" \x01(\tB\x04\xe2A\x01\x02R\x05extra\x12\x1a\n" +
	"\x05quote\x18\f \x01(\tB\x04\xe2A\x01\x02R\x05quote2\xc3\x04\n" +
	"\aMessage\x12b\n" +
	"\x06Revoke\x12\x19.web.MessageRevokeRequest\x1a\x1a.web.MessageRevokeResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/message/revoke\x12b\n" +
	"\x06Delete\x12\x19.web.MessageDeleteRequest\x1a\x1a.web.MessageDeleteResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/message/delete\x12f\n" +
	"\arecords\x12\x1a.web.MessageRecordsRequest\x1a\x1b.web.MessageRecordsResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/message/records\x12\x83\x01\n" +
	"\x0eHistoryRecords\x12!.web.MessageHistoryRecordsRequest\x1a\".web.MessageHistoryRecordsResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/message/history-records\x12\x81\x01\n" +
	"\x0eForwardRecords\x12!.web.MessageForwardRecordsRequest\x1a .web.MessageRecordsClearResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/message/forward-recordsB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_message_proto_rawDescOnce sync.Once
	file_web_v1_message_proto_rawDescData []byte
)

func file_web_v1_message_proto_rawDescGZIP() []byte {
	file_web_v1_message_proto_rawDescOnce.Do(func() {
		file_web_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_message_proto_rawDesc), len(file_web_v1_message_proto_rawDesc)))
	})
	return file_web_v1_message_proto_rawDescData
}

var file_web_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_web_v1_message_proto_goTypes = []any{
	(*MessageRevokeRequest)(nil),          // 0: web.MessageRevokeRequest
	(*MessageRevokeResponse)(nil),         // 1: web.MessageRevokeResponse
	(*MessageDeleteRequest)(nil),          // 2: web.MessageDeleteRequest
	(*MessageDeleteResponse)(nil),         // 3: web.MessageDeleteResponse
	(*MessageRecordsRequest)(nil),         // 4: web.MessageRecordsRequest
	(*MessageRecordsResponse)(nil),        // 5: web.MessageRecordsResponse
	(*MessageHistoryRecordsRequest)(nil),  // 6: web.MessageHistoryRecordsRequest
	(*MessageHistoryRecordsResponse)(nil), // 7: web.MessageHistoryRecordsResponse
	(*MessageForwardRecordsRequest)(nil),  // 8: web.MessageForwardRecordsRequest
	(*MessageRecordsClearResponse)(nil),   // 9: web.MessageRecordsClearResponse
	(*MessageRecord)(nil),                 // 10: web.MessageRecord
}
var file_web_v1_message_proto_depIdxs = []int32{
	10, // 0: web.MessageRecordsResponse.items:type_name -> web.MessageRecord
	10, // 1: web.MessageHistoryRecordsResponse.items:type_name -> web.MessageRecord
	10, // 2: web.MessageRecordsClearResponse.items:type_name -> web.MessageRecord
	0,  // 3: web.Message.Revoke:input_type -> web.MessageRevokeRequest
	2,  // 4: web.Message.Delete:input_type -> web.MessageDeleteRequest
	4,  // 5: web.Message.records:input_type -> web.MessageRecordsRequest
	6,  // 6: web.Message.HistoryRecords:input_type -> web.MessageHistoryRecordsRequest
	8,  // 7: web.Message.ForwardRecords:input_type -> web.MessageForwardRecordsRequest
	1,  // 8: web.Message.Revoke:output_type -> web.MessageRevokeResponse
	3,  // 9: web.Message.Delete:output_type -> web.MessageDeleteResponse
	5,  // 10: web.Message.records:output_type -> web.MessageRecordsResponse
	7,  // 11: web.Message.HistoryRecords:output_type -> web.MessageHistoryRecordsResponse
	9,  // 12: web.Message.ForwardRecords:output_type -> web.MessageRecordsClearResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_web_v1_message_proto_init() }
func file_web_v1_message_proto_init() {
	if File_web_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_message_proto_rawDesc), len(file_web_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_message_proto_goTypes,
		DependencyIndexes: file_web_v1_message_proto_depIdxs,
		MessageInfos:      file_web_v1_message_proto_msgTypes,
	}.Build()
	File_web_v1_message_proto = out.File
	file_web_v1_message_proto_goTypes = nil
	file_web_v1_message_proto_depIdxs = nil
}
