// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IMessageHandler BFF 接口
type IMessageHandler interface {
	Revoke(ctx context.Context, in *MessageRevokeRequest) (*MessageRevokeResponse, error)

	Delete(ctx context.Context, in *MessageDeleteRequest) (*MessageDeleteResponse, error)
	// 获取会话消息记录
	Records(ctx context.Context, in *MessageRecordsRequest) (*MessageRecordsResponse, error)
	// 获取会话历史消息记录
	HistoryRecords(ctx context.Context, in *MessageHistoryRecordsRequest) (*MessageHistoryRecordsResponse, error)
	// 转发消息记录
	ForwardRecords(ctx context.Context, in *MessageForwardRecordsRequest) (*MessageRecordsClearResponse, error)
}

// RegisterMessageHandler 注册服务路由处理器
func RegisterMessageHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler IMessageHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/message/revoke", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in MessageRevokeRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Revoke(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/message/delete", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in MessageDeleteRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Delete(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/message/records", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in MessageRecordsRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Records(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/message/history-records", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in MessageHistoryRecordsRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.HistoryRecords(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/message/forward-records", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in MessageForwardRecordsRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.ForwardRecords(ctx.Request.Context(), &in)
	}))

}
