// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// ITalkHandler BFF 接口
type ITalkHandler interface {

	// 会话创建接口
	SessionCreate(ctx context.Context, in *TalkSessionCreateRequest) (*TalkSessionCreateResponse, error)
	// 会话删除接口
	SessionDelete(ctx context.Context, in *TalkSessionDeleteRequest) (*TalkSessionDeleteResponse, error)
	// 会话置顶接口
	SessionTop(ctx context.Context, in *TalkSessionTopRequest) (*TalkSessionTopResponse, error)
	// 会话免打扰接口
	SessionDisturb(ctx context.Context, in *TalkSessionDisturbRequest) (*TalkSessionDisturbResponse, error)
	// 会话列表接口
	SessionList(ctx context.Context, in *TalkSessionListRequest) (*TalkSessionListResponse, error)
	// 会话未读数清除接口
	SessionClearUnreadNum(ctx context.Context, in *TalkSessionClearUnreadNumRequest) (*TalkSessionClearUnreadNumResponse, error)
}

// RegisterTalkHandler 注册服务路由处理器
func RegisterTalkHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler ITalkHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/talk/session-create", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TalkSessionCreateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SessionCreate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/talk/session-delete", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TalkSessionDeleteRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SessionDelete(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/talk/session-top", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TalkSessionTopRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SessionTop(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/talk/session-disturb", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TalkSessionDisturbRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SessionDisturb(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/talk/session-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TalkSessionListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SessionList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/talk/session-clear-unread-num", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TalkSessionClearUnreadNumRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SessionClearUnreadNum(ctx.Request.Context(), &in)
	}))

}
