// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package admin

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IResourceHandler BFF 接口
type IResourceHandler interface {
	List(ctx context.Context, req *ResourceListRequest) (*ResourceListResponse, error)
	Create(ctx context.Context, req *ResourceCreateRequest) (*ResourceCreateResponse, error)
	Update(ctx context.Context, req *ResourceUpdateRequest) (*ResourceUpdateResponse, error)
	Delete(ctx context.Context, req *ResourceDeleteRequest) (*ResourceDeleteResponse, error)
}

// RegisterResourceHandler 注册服务路由处理器
func RegisterResourceHandler(r gin.IRoutes, s interface {
	ShouldProto(c *gin.Context, in any) error
	ErrorResponse(c *gin.Context, err error)
	SuccessResponse(c *gin.Context, data any)
}, handler IResourceHandler) {
	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/backend/resource/list", func(c *gin.Context) {
		var in ResourceListRequest
		if err := s.ShouldProto(c, &in); err != nil {
			s.ErrorResponse(c, err)
			return
		}

		data, err := handler.List(c.Request.Context(), &in)
		if err != nil {
			s.ErrorResponse(c, err)
			return
		}

		s.SuccessResponse(c, data)
	})

	r.POST("/backend/resource/create", func(c *gin.Context) {
		var in ResourceCreateRequest
		if err := s.ShouldProto(c, &in); err != nil {
			s.ErrorResponse(c, err)
			return
		}

		data, err := handler.Create(c.Request.Context(), &in)
		if err != nil {
			s.ErrorResponse(c, err)
			return
		}

		s.SuccessResponse(c, data)
	})

	r.POST("/backend/resource/update", func(c *gin.Context) {
		var in ResourceUpdateRequest
		if err := s.ShouldProto(c, &in); err != nil {
			s.ErrorResponse(c, err)
			return
		}

		data, err := handler.Update(c.Request.Context(), &in)
		if err != nil {
			s.ErrorResponse(c, err)
			return
		}

		s.SuccessResponse(c, data)
	})

	r.POST("/backend/resource/delete", func(c *gin.Context) {
		var in ResourceDeleteRequest
		if err := s.ShouldProto(c, &in); err != nil {
			s.ErrorResponse(c, err)
			return
		}

		data, err := handler.Delete(c.Request.Context(), &in)
		if err != nil {
			s.ErrorResponse(c, err)
			return
		}

		s.SuccessResponse(c, data)
	})

}
