// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package admin

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IRoleHandler BFF 接口
type IRoleHandler interface {
	List(ctx context.Context, req *RoleListRequest) (*RoleListResponse, error)
	Create(ctx context.Context, req *RoleCreateRequest) (*RoleCreateResponse, error)
	Update(ctx context.Context, req *RoleUpdateRequest) (*RoleUpdateResponse, error)
}

// RegisterRoleHandler 注册服务路由处理器
func RegisterRoleHandler(r gin.IRoutes, s interface {
	ShouldProto(c *gin.Context, in any) error
	ErrorResponse(c *gin.Context, err error)
	SuccessResponse(c *gin.Context, data any)
}, handler IRoleHandler) {
	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/backend/role/list", func(c *gin.Context) {
		var in RoleListRequest
		if err := s.ShouldProto(c, &in); err != nil {
			s.ErrorResponse(c, err)
			return
		}

		data, err := handler.List(c.Request.Context(), &in)
		if err != nil {
			s.ErrorResponse(c, err)
			return
		}

		s.SuccessResponse(c, data)
	})

	r.POST("/backend/role/create", func(c *gin.Context) {
		var in RoleCreateRequest
		if err := s.ShouldProto(c, &in); err != nil {
			s.ErrorResponse(c, err)
			return
		}

		data, err := handler.Create(c.Request.Context(), &in)
		if err != nil {
			s.ErrorResponse(c, err)
			return
		}

		s.SuccessResponse(c, data)
	})

	r.POST("/backend/role/update", func(c *gin.Context) {
		var in RoleUpdateRequest
		if err := s.ShouldProto(c, &in); err != nil {
			s.ErrorResponse(c, err)
			return
		}

		data, err := handler.Update(c.Request.Context(), &in)
		if err != nil {
			s.ErrorResponse(c, err)
			return
		}

		s.SuccessResponse(c, data)
	})

}
