// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package admin

import (
	"context"

	"github.com/gin-gonic/gin"
)

// ITotpHandler BFF 接口
type ITotpHandler interface {

	// 获取双因子认证状态接口
	Status(ctx context.Context, in *TotpStatusRequest) (*TotpStatusResponse, error)
	// 关闭双因子认证接口
	Close(ctx context.Context, in *TotpCloseRequest) (*TotpCloseResponse, error)
	// 初始化双因子认证接口
	Init(ctx context.Context, in *TotpInitRequest) (*TotpInitResponse, error)
	// 提交双因子认证接口
	Submit(ctx context.Context, in *TotpSubmitRequest) (*TotpSubmitResponse, error)
	// 获取双因子认证二维码接口
	Qrcode(ctx context.Context, in *TotpQrcodeRequest) (*TotpQrcodeResponse, error)
}

// RegisterTotpHandler 注册服务路由处理器
func RegisterTotpHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler ITotpHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/backend/totp/status", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TotpStatusRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Status(ctx.Request.Context(), &in)
	}))

	r.POST("/backend/totp/close", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TotpCloseRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Close(ctx.Request.Context(), &in)
	}))

	r.POST("/backend/totp/init", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TotpInitRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Init(ctx.Request.Context(), &in)
	}))

	r.POST("/backend/totp/submit", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TotpSubmitRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Submit(ctx.Request.Context(), &in)
	}))

	r.POST("/backend/totp/qrcode", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in TotpQrcodeRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Qrcode(ctx.Request.Context(), &in)
	}))

}
